### ISSUE TITLE
AssertionError while using Clone Voice grenerated file

### ISSUE THREAD

**Issue by HalfMAI** [C0untFloyd/bark-gui#21] opened 2023-05-15 09:53 UTC
1. I input a .wav file and generated .npz with the corresponding text content
2. I have the following problem when using my file

Version Info:
Launching Bark GUI - please edit windows_run.bat to customize commandline arguments
Check for Updates? [y/n]n
smallmodels=True
enablemps=False
offloadcpu=False
forcecpu=False
autolaunch=True

Preloading Models

Loading text_small model from ./models\text.pt to cuda
Loading coarse_small model from ./models\coarse.pt to cuda
Loading fine_small model from ./models\fine.pt to cuda
Launching Bark UI Enhanced v0.4.6 Server

---
AssertionError
`
Generating Text (1/1) -> custom\MeMyselfAndI (Seed 4124450773):`WOMAN: I would like an oatmilk latte please. MAN: Wow, that's expensive!`
Traceback (most recent call last):
  File "E:\bark-gui\installer_files\env\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\bark-gui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1320, in process_api
    result = await self.call_function(
  File "E:\bark-gui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1048, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\bark-gui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\bark-gui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\bark-gui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\bark-gui\installer_files\env\lib\site-packages\gradio\helpers.py", line 589, in tracked_fn
    response = fn(*args)
  File "E:\bark-gui\bark-gui\webui.py", line 91, in generate_text_to_speech
    audio_array = generate_with_settings(text_prompt=text, voice_name=selected_speaker, semantic_temp=text_temp, coarse_temp=waveform_temp, eos_p=eos_prob)
  File "E:\bark-gui\bark-gui\bark\api.py", line 19, in generate_with_settings
    x_coarse_gen = generate_coarse(
  File "E:\bark-gui\bark-gui\bark\generation.py", line 603, in generate_coarse
    round(x_coarse_history.shape[-1] / len(x_semantic_history), 1)
AssertionError
`
![image](https://github.com/C0untFloyd/bark-gui/assets/5293796/d6ed822e-a521-43a0-922a-1bd15796b054)

**Comment by C0untFloyd** [comment] 2023-05-16 18:29
This is a duplicate of issues #11  and #12 
I'm guessing your cloned voice is much longer than the suggested 4 seconds of audio. You could either turn off generation history or just comment out the assert in line 590.

**Closed by C0untFloyd** 2023-05-16 18:29 UTC
