### ISSUE TITLE
error StartBark.bat

### ISSUE THREAD

**Issue by Tribuzeus** [C0untFloyd/bark-gui#41] opened 2023-06-25 21:52 UTC
Error in install:

     File "C:\Users\green\AppData\Local\Temp\pip-build-env-z0acumc2\overlay\Lib\site-packages\setuptools\msvc.py", line 168, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "C:\Users\green\Desktop\bark_win\bark-gui\webui.py", line 5, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

Done!
Pressione qualquer tecla para continuar. . .
...
AND
...
Error in StartBartk.bat:

raceback (most recent call last):
  File "C:\Users\green\Desktop\bark-gui-main\webui.py", line 5, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
Pressione qualquer tecla para continuar. . .

**Comment by C0untFloyd** [comment] 2023-06-26 16:34
I think this is a duplicate of #35 and #38. Please use the windows-run.bat on Windows.

**Closed by C0untFloyd** 2023-06-26 16:34 UTC
